#url: "" # the base hostname & protocol for your site, e.g. http://example.com
#baseurl: "" # the subpath of your site, e.g. /blog
title: "Domain Project" # the name of your site, e.g. ACME Corp.
description: "Taming Heterogeneous Computing Complexity with Full-Stack Governance of Domain-Specific Languages"